{
 "title": "kandula",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "time_processing_request_sum{",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time_processing_request_sum{endpoint=\"home\"}"
    },
    {
     "expr": "time_processing_request_count{endpoint=\"home\"}"
    }
   ]
  },
  {
   "title": "time_processing_request_created gauge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "time_processing_request_created{endpoint=\"scheduler\"}"
    },
    {
     "expr": "time_processing_request_created{endpoint=\"instances\"}"
    }
   ]
  },
  {
   "title": "process_open_fds gauge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\":9100\", job=\"kandula-app\", pod=\"kandula-app-service-default-2ef8b6059d51\"}"
    }
   ]
  },
  {
   "title": "process_max_fds gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\":9100\", job=\"kandula-app\", pod=\"kandula-app-service-default-2ef8b6059d51\"}\r\n"
    }
   ]
  }
 ]
}