apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::031034181336:role/opsschool-eks-duhwjxqk2021010511062606710000000a
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::461307513197:role/jekins-role
      username: jekins-role
      groups: 
        - system:system
