global:
  enabled: false
  image: "consul:1.11.1"
  datacenter: opsschool
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
client:
  enabled: true
  # Set this to true to expose the Consul clients using the Kubernetes node
  # IPs. If false, the pod IPs must be routable from the external servers.
  exposeGossipPorts: true
  # Consul Cluster Outside K8S leader IP
  join:
    - "provider=aws tag_key=consul_server tag_value=true"
  grpc: true
  nodeMeta:
    pod-name: ${HOSTNAME}
    host-ip: ${HOST_IP}
dns:
  # @type: boolean
  enabled: true
syncCatalog:
  enabled: true
  k8sAllowNamespaces: ["*"]
  k8sDenyNamespaces: []
